/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SaaSPlan } from "./SaaSPlan";
import { SaaSPlanCountArgs } from "./SaaSPlanCountArgs";
import { SaaSPlanFindManyArgs } from "./SaaSPlanFindManyArgs";
import { SaaSPlanFindUniqueArgs } from "./SaaSPlanFindUniqueArgs";
import { DeleteSaaSPlanArgs } from "./DeleteSaaSPlanArgs";
import { SaaSPlanService } from "../saaSPlan.service";
@graphql.Resolver(() => SaaSPlan)
export class SaaSPlanResolverBase {
  constructor(protected readonly service: SaaSPlanService) {}

  async _saaSPlansMeta(
    @graphql.Args() args: SaaSPlanCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SaaSPlan])
  async saaSPlans(
    @graphql.Args() args: SaaSPlanFindManyArgs
  ): Promise<SaaSPlan[]> {
    return this.service.saaSPlans(args);
  }

  @graphql.Query(() => SaaSPlan, { nullable: true })
  async saaSPlan(
    @graphql.Args() args: SaaSPlanFindUniqueArgs
  ): Promise<SaaSPlan | null> {
    const result = await this.service.saaSPlan(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SaaSPlan)
  async deleteSaaSPlan(
    @graphql.Args() args: DeleteSaaSPlanArgs
  ): Promise<SaaSPlan | null> {
    try {
      return await this.service.deleteSaaSPlan(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
