/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PlanService } from "../plan.service";
import { PlanCreateInput } from "./PlanCreateInput";
import { Plan } from "./Plan";
import { PlanFindManyArgs } from "./PlanFindManyArgs";
import { PlanWhereUniqueInput } from "./PlanWhereUniqueInput";
import { PlanUpdateInput } from "./PlanUpdateInput";
import { SubscriptionFindManyArgs } from "../../subscription/base/SubscriptionFindManyArgs";
import { Subscription } from "../../subscription/base/Subscription";
import { SubscriptionWhereUniqueInput } from "../../subscription/base/SubscriptionWhereUniqueInput";

export class PlanControllerBase {
  constructor(protected readonly service: PlanService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Plan })
  async createPlan(@common.Body() data: PlanCreateInput): Promise<Plan> {
    return await this.service.createPlan({
      data: data,
      select: {
        createdAt: true,
        description: true,
        durationDays: true,
        id: true,
        numberOfUsers: true,
        planName: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Plan] })
  @ApiNestedQuery(PlanFindManyArgs)
  async plans(@common.Req() request: Request): Promise<Plan[]> {
    const args = plainToClass(PlanFindManyArgs, request.query);
    return this.service.plans({
      ...args,
      select: {
        createdAt: true,
        description: true,
        durationDays: true,
        id: true,
        numberOfUsers: true,
        planName: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Plan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async plan(
    @common.Param() params: PlanWhereUniqueInput
  ): Promise<Plan | null> {
    const result = await this.service.plan({
      where: params,
      select: {
        createdAt: true,
        description: true,
        durationDays: true,
        id: true,
        numberOfUsers: true,
        planName: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Plan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePlan(
    @common.Param() params: PlanWhereUniqueInput,
    @common.Body() data: PlanUpdateInput
  ): Promise<Plan | null> {
    try {
      return await this.service.updatePlan({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          durationDays: true,
          id: true,
          numberOfUsers: true,
          planName: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Plan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePlan(
    @common.Param() params: PlanWhereUniqueInput
  ): Promise<Plan | null> {
    try {
      return await this.service.deletePlan({
        where: params,
        select: {
          createdAt: true,
          description: true,
          durationDays: true,
          id: true,
          numberOfUsers: true,
          planName: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/subscriptions")
  @ApiNestedQuery(SubscriptionFindManyArgs)
  async findSubscriptions(
    @common.Req() request: Request,
    @common.Param() params: PlanWhereUniqueInput
  ): Promise<Subscription[]> {
    const query = plainToClass(SubscriptionFindManyArgs, request.query);
    const results = await this.service.findSubscriptions(params.id, {
      ...query,
      select: {
        createdAt: true,
        endDate: true,
        id: true,
        isActive: true,

        plan: {
          select: {
            id: true,
          },
        },

        startDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/subscriptions")
  async connectSubscriptions(
    @common.Param() params: PlanWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        connect: body,
      },
    };
    await this.service.updatePlan({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/subscriptions")
  async updateSubscriptions(
    @common.Param() params: PlanWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        set: body,
      },
    };
    await this.service.updatePlan({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/subscriptions")
  async disconnectSubscriptions(
    @common.Param() params: PlanWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        disconnect: body,
      },
    };
    await this.service.updatePlan({
      where: params,
      data,
      select: { id: true },
    });
  }
}
